 
version: '3.3'

services:
  glpi_mysql :
    image : mysql:8-debian
    container_name : glpi_mysql
    hostname: mysql
    restart: always
    expose :
      - "3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - glpi_sqldata:/var/lib/mysql
    networks:
      glpi_project:
  glpi:
    image: debian:11
    container_name: glpi
    hostname: glpi
    restart: always
    ports:
      - 4443:443
    env_file:
      - secrets.env
    volumes:
      - ./ssl/ssl.key:/etc/ssl/glpi.key
      - ./ssl/ssl.crt:/etc/ssl/glpi.crt
      - ./front/vhost_glpi.conf:/etc/nginx/sites-available/glpi.conf
      - ./scripts/glpi-setup.sh:/usr/local/bin/glpi-setup.sh
      - glpi_data:/var/www/html/glpi/
    networks:
      glpi_project:
    depends_on:
      - glpi_mysql
    command: /usr/local/bin/glpi-setup.sh

 
networks:
  glpi_project:

volumes:
  glpi_sqldata:
  glpi_data:

